# services:
#   with-docker-multi-env-development:
#     build:
#       context: ./
#       dockerfile: Dockerfile
#     image: with-docker-multi-env-development
#     ports:
#       - "3001:3000"

version: '3.8'

services:
  app:
    build:
      context: . # Build from the current directory
    image: ghcr.io/hijaz-tariq/eqalam-beta:v0.04 # Update the image tag
    ports:
      - "3000:3000" # Map container port 3000 to host port 3000
    env_file:
      - .env # Load environment variables from the .env file
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
